# Jekyll Resume Theme

# Site settings
title: Adriano Ray
name: Adriano Ray
email: adriano@wimse.se
description: Min CV
baseurl: "http://adrianoray.github.io/"
url: "http://mattcouchman.co.uk/jekyll-resume/"
location: Göteborg, SE
languages: HTML, CSS and Javascript
twitter_username: mattcouchman
github_username:  mattcouchman
codepen_username:  mattcouchman
email_address: some@email.com

# Build settings
markdown: kramdown
