destination: ../site
title: Adriano Ray
name: Adriano Ray
email: adriano@wimse.se
description: Min CV
baseurl: ""
url: "http://adrianoray.github.io/"
location: Göteborg, SE
email_address: adriano@wimse.se

# Build settings
markdown: kramdown

prose:
    rooturl: '_data'
    siteurl: 'http://adrianoray.github.io/'
